version: 2

builds:
  - id: gofscraper
    main: ./cmd/gofscraper
    binary: gofscraper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X gofscraper/pkg/version.Version={{.Version}}
      - -X gofscraper/pkg/version.Commit={{.ShortCommit}}
      - -X gofscraper/pkg/version.BuildDate={{.Date}}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "gofscraper_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
